name: Upload info.json to cos when file changed

on:
  push:
    branches: [ "TONX" ]
    paths: [ "info.json" ]

permissions:
  contents: read
  
jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -c "import sys; print(sys.version)"
    - name: Put Request To Cos
      env:
        COS_HOST: ${{ secrets.COS_HOST }}
      run: |
        import os
        import requests
        
        file = './info.json'
        size = os.stat(file).st_size
        with open (file, 'rb') as file_object:
          contents = file_object.read()
        
        url = "https://" + str(os.environ.get('COS_HOST')) + "/info.json"
        headers = {'Content-Type': 'application/json', 'Host': os.environ.get('COS_HOST') }
        
        req = requests.put(url, data = contents, headers = headers)
        
        print('File Size: ' + str(size))
        print('Status Code: ' + str(req.status_code))
        
        if req.status_code == 200: print('√ Successfully uploaded to Tencent Cloud Cos!')
        else: print('× Upload to Tencent Cloud Cos failed:\n\n' + req.text)
        
      shell: python
